// GENERATED by scripts/generate-type-fixtures.ts (seed 424242) — do not edit by hand.
// target=25 guardDensity=0.25 schemaDensity=0.5
import { z } from "zod";
import { defineApp } from "../../../src/core/app";
import { defineModule } from "../../../src/core/module";
import { route } from "../../../src/core/route";
import { guard } from "../../../src/core/guard";
import { json, text, problem } from "../../../src/core/response";

const authGuard = guard({
  name: "authGuard",
  handler: () => json(401, { error: 'unauthorized' }),
});
const adminGuard = guard({
  name: "adminGuard",
  handler: () => problem(403, { title: 'Forbidden' }),
});

// --- module routes (1/3 of total) ---
const featureModule = defineModule({
  name: "featureModule",
  routes: {
    "/res0": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 0 }),
      }),
    },
    "/res3": {
      GET: route({
        query: z.object({ page3: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 3 }),
      }),
    },
    "/res6": {
      POST: route({
        body: z.object({ name6: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 6 }),
      }),
    },
    "/res9": new Response("raw 9"),
    "/res12": new Response("raw 12"),
    "/res15/:id15": {
      PUT: route({
        params: z.object({ id15: z.coerce.number() }),
        body: z.object({ name15: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 15 }),
      }),
    },
    "/res18": {
      PUT: route({
        body: z.object({ name18: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 18 }),
      }),
    },
    "/res21/:id21": {
      PATCH: route({
        before: [authGuard, adminGuard],
        params: z.object({ id21: z.coerce.number() }),
        body: z.object({ name21: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 21 }),
      }),
    },
    "/res24/:id24": {
      PATCH: route({
        params: z.object({ id24: z.coerce.number() }),
        body: z.object({ name24: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 24 }),
      }),
    },
  },
});

export const app = defineApp({
  routes: {
    "/res1/:id1": {
      PATCH: route({
        params: z.object({ id1: z.coerce.number() }),
        body: z.object({ name1: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 1 }),
      }),
    },
    "/res2/:id2": {
      PATCH: route({
        params: z.object({ id2: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 2 }),
      }),
    },
    "/res4": {
      GET: route({
        query: z.object({ page4: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 4 }),
      }),
    },
    "/res5/:id5": {
      POST: route({
        params: z.object({ id5: z.coerce.number() }),
        body: z.object({ name5: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 5 }),
      }),
    },
    "/res7": new Response("raw 7"),
    "/res8/:id8": {
      POST: route({
        params: z.object({ id8: z.coerce.number() }),
        body: z.object({ name8: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 8 }),
      }),
    },
    "/res10": {
      POST: route({
        body: z.object({ name10: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 10 }),
      }),
    },
    "/res11/:id11": {
      POST: route({
        params: z.object({ id11: z.coerce.number() }),
        body: z.object({ name11: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 11 }),
      }),
    },
    "/res13": {
      PATCH: route({
        body: z.object({ name13: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 13 }),
      }),
    },
    "/res14/:id14": new Response("raw 14"),
    "/res16/:id16": {
      DELETE: route({
        params: z.object({ id16: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 16 }),
      }),
    },
    "/res17/:id17": {
      PATCH: route({
        before: [authGuard],
        params: z.object({ id17: z.coerce.number() }),
        body: z.object({ name17: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 17 }),
      }),
    },
    "/res19/:id19": {
      DELETE: route({
        params: z.object({ id19: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 19 }),
      }),
    },
    "/res20": {
      POST: route({
        before: [authGuard],
        body: z.object({ name20: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 20 }),
      }),
    },
    "/res22/:id22": {
      POST: route({
        params: z.object({ id22: z.coerce.number() }),
        body: z.object({ name22: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 22 }),
      }),
    },
    "/res23": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 23 }),
      }),
    },
  },
  modules: [featureModule],
});

export default app;