// GENERATED by scripts/generate-type-fixtures.ts (seed 424242) — do not edit by hand.
// target=500 guardDensity=0.25 schemaDensity=0.5
import { z } from "zod";
import { defineApp } from "../../../src/core/app";
import { defineModule } from "../../../src/core/module";
import { route } from "../../../src/core/route";
import { guard } from "../../../src/core/guard";
import { json, text, problem } from "../../../src/core/response";

const authGuard = guard({
  name: "authGuard",
  handler: () => json(401, { error: 'unauthorized' }),
});
const adminGuard = guard({
  name: "adminGuard",
  handler: () => problem(403, { title: 'Forbidden' }),
});

// --- module routes (1/3 of total) ---
const featureModule = defineModule({
  name: "featureModule",
  routes: {
    "/res0": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 0 }),
      }),
    },
    "/res3": {
      GET: route({
        query: z.object({ page3: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 3 }),
      }),
    },
    "/res6": {
      POST: route({
        body: z.object({ name6: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 6 }),
      }),
    },
    "/res9": new Response("raw 9"),
    "/res12": new Response("raw 12"),
    "/res15/:id15": {
      PUT: route({
        params: z.object({ id15: z.coerce.number() }),
        body: z.object({ name15: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 15 }),
      }),
    },
    "/res18": {
      PUT: route({
        body: z.object({ name18: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 18 }),
      }),
    },
    "/res21/:id21": {
      PATCH: route({
        before: [authGuard, adminGuard],
        params: z.object({ id21: z.coerce.number() }),
        body: z.object({ name21: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 21 }),
      }),
    },
    "/res24/:id24": {
      PATCH: route({
        params: z.object({ id24: z.coerce.number() }),
        body: z.object({ name24: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 24 }),
      }),
    },
    "/res27": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 27 }),
      }),
    },
    "/res30": {
      GET: route({
        query: z.object({ page30: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 30 }),
      }),
    },
    "/res33/:id33": {
      PATCH: route({
        params: z.object({ id33: z.coerce.number() }),
        body: z.object({ name33: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 33 }),
      }),
    },
    "/res36": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 36 }),
      }),
    },
    "/res39": new Response("raw 39"),
    "/res42": {
      GET: route({
        handler: () => json(200, { ok: true, idx: 42 }),
      }),
    },
    "/res45/:id45": {
      POST: route({
        params: z.object({ id45: z.coerce.number() }),
        handler: () => json(201, { ok: true, idx: 45 }),
      }),
    },
    "/res48": {
      PUT: route({
        body: z.object({ name48: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 48 }),
      }),
    },
    "/res51/:id51": {
      DELETE: route({
        params: z.object({ id51: z.coerce.number() }),
        body: z.object({ name51: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 51 }),
      }),
    },
    "/res54": new Response("raw 54"),
    "/res57/:id57": {
      DELETE: route({
        params: z.object({ id57: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 57 }),
      }),
    },
    "/res60": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 60 }),
      }),
    },
    "/res63": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 63 }),
      }),
    },
    "/res66/:id66": {
      GET: route({
        params: z.object({ id66: z.coerce.number() }),
        query: z.object({ page66: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 66 }),
      }),
    },
    "/res69": {
      PUT: route({
        body: z.object({ name69: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 69 }),
      }),
    },
    "/res72": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 72 }),
      }),
    },
    "/res75": {
      PATCH: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 75 }),
      }),
    },
    "/res78/:id78": {
      DELETE: route({
        params: z.object({ id78: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 78 }),
      }),
    },
    "/res81": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 81 }),
      }),
    },
    "/res84/:id84": {
      PUT: route({
        params: z.object({ id84: z.coerce.number() }),
        body: z.object({ name84: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 84 }),
      }),
    },
    "/res87/:id87": {
      PUT: route({
        params: z.object({ id87: z.coerce.number() }),
        body: z.object({ name87: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 87 }),
      }),
    },
    "/res90/:id90": {
      DELETE: route({
        params: z.object({ id90: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 90 }),
      }),
    },
    "/res93": {
      POST: route({
        before: [authGuard],
        body: z.object({ name93: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 93 }),
      }),
    },
    "/res96/:id96": {
      PATCH: route({
        params: z.object({ id96: z.coerce.number() }),
        body: z.object({ name96: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 96 }),
      }),
    },
    "/res99": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 99 }),
      }),
    },
    "/res102": {
      PUT: route({
        before: [authGuard],
        body: z.object({ name102: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 102 }),
      }),
    },
    "/res105/:id105": {
      PUT: route({
        params: z.object({ id105: z.coerce.number() }),
        body: z.object({ name105: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 105 }),
      }),
    },
    "/res108": {
      DELETE: route({
        body: z.object({ name108: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 108 }),
      }),
    },
    "/res111": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 111 }),
      }),
    },
    "/res114/:id114": {
      POST: route({
        params: z.object({ id114: z.coerce.number() }),
        body: z.object({ name114: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 114 }),
      }),
    },
    "/res117/:id117": {
      GET: route({
        params: z.object({ id117: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 117 }),
      }),
    },
    "/res120": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 120 }),
      }),
    },
    "/res123": new Response("raw 123"),
    "/res126/:id126": {
      DELETE: route({
        before: [authGuard, adminGuard],
        params: z.object({ id126: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 126 }),
      }),
    },
    "/res129/:id129": {
      POST: route({
        params: z.object({ id129: z.coerce.number() }),
        handler: () => json(201, { ok: true, idx: 129 }),
      }),
    },
    "/res132": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 132 }),
      }),
    },
    "/res135": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 135 }),
      }),
    },
    "/res138/:id138": {
      PUT: route({
        before: [authGuard, adminGuard],
        params: z.object({ id138: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 138 }),
      }),
    },
    "/res141": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 141 }),
      }),
    },
    "/res144": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 144 }),
      }),
    },
    "/res147/:id147": {
      GET: route({
        params: z.object({ id147: z.coerce.number() }),
        query: z.object({ page147: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 147 }),
      }),
    },
    "/res150": {
      POST: route({
        body: z.object({ name150: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 150 }),
      }),
    },
    "/res153": {
      GET: route({
        before: [authGuard, adminGuard],
        handler: () => json(200, { ok: true, idx: 153 }),
      }),
    },
    "/res156": {
      GET: route({
        handler: () => json(200, { ok: true, idx: 156 }),
      }),
    },
    "/res159/:id159": {
      GET: route({
        params: z.object({ id159: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 159 }),
      }),
    },
    "/res162/:id162": {
      PATCH: route({
        params: z.object({ id162: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 162 }),
      }),
    },
    "/res165": {
      PATCH: route({
        body: z.object({ name165: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 165 }),
      }),
    },
    "/res168": {
      DELETE: route({
        body: z.object({ name168: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 168 }),
      }),
    },
    "/res171": new Response("raw 171"),
    "/res174/:id174": {
      PUT: route({
        params: z.object({ id174: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 174 }),
      }),
    },
    "/res177/:id177": {
      PATCH: route({
        params: z.object({ id177: z.coerce.number() }),
        body: z.object({ name177: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 177 }),
      }),
    },
    "/res180": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 180 }),
      }),
    },
    "/res183": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 183 }),
      }),
    },
    "/res186/:id186": {
      GET: route({
        params: z.object({ id186: z.coerce.number() }),
        query: z.object({ page186: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 186 }),
      }),
    },
    "/res189/:id189": new Response("raw 189"),
    "/res192/:id192": new Response("raw 192"),
    "/res195": {
      GET: route({
        before: [authGuard, adminGuard],
        query: z.object({ page195: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 195 }),
      }),
    },
    "/res198": new Response("raw 198"),
    "/res201": {
      GET: route({
        handler: () => json(200, { ok: true, idx: 201 }),
      }),
    },
    "/res204/:id204": {
      PUT: route({
        params: z.object({ id204: z.coerce.number() }),
        body: z.object({ name204: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 204 }),
      }),
    },
    "/res207": new Response("raw 207"),
    "/res210": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 210 }),
      }),
    },
    "/res213": new Response("raw 213"),
    "/res216/:id216": {
      GET: route({
        before: [authGuard, adminGuard],
        params: z.object({ id216: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 216 }),
      }),
    },
    "/res219/:id219": {
      GET: route({
        before: [authGuard, adminGuard],
        params: z.object({ id219: z.coerce.number() }),
        query: z.object({ page219: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 219 }),
      }),
    },
    "/res222": {
      DELETE: route({
        body: z.object({ name222: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 222 }),
      }),
    },
    "/res225": {
      GET: route({
        before: [authGuard, adminGuard],
        handler: () => json(200, { ok: true, idx: 225 }),
      }),
    },
    "/res228": {
      PUT: route({
        before: [authGuard, adminGuard],
        handler: () => json(200, { ok: true, idx: 228 }),
      }),
    },
    "/res231": {
      GET: route({
        handler: () => json(200, { ok: true, idx: 231 }),
      }),
    },
    "/res234": {
      PUT: route({
        body: z.object({ name234: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 234 }),
      }),
    },
    "/res237": {
      PUT: route({
        body: z.object({ name237: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 237 }),
      }),
    },
    "/res240": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 240 }),
      }),
    },
    "/res243": {
      POST: route({
        body: z.object({ name243: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 243 }),
      }),
    },
    "/res246/:id246": {
      DELETE: route({
        params: z.object({ id246: z.coerce.number() }),
        body: z.object({ name246: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 246 }),
      }),
    },
    "/res249": {
      DELETE: route({
        body: z.object({ name249: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 249 }),
      }),
    },
    "/res252": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 252 }),
      }),
    },
    "/res255": new Response("raw 255"),
    "/res258/:id258": new Response("raw 258"),
    "/res261": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 261 }),
      }),
    },
    "/res264/:id264": {
      POST: route({
        params: z.object({ id264: z.coerce.number() }),
        body: z.object({ name264: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 264 }),
      }),
    },
    "/res267": {
      GET: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 267 }),
      }),
    },
    "/res270/:id270": new Response("raw 270"),
    "/res273": {
      DELETE: route({
        body: z.object({ name273: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 273 }),
      }),
    },
    "/res276": new Response("raw 276"),
    "/res279/:id279": {
      GET: route({
        params: z.object({ id279: z.coerce.number() }),
        query: z.object({ page279: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 279 }),
      }),
    },
    "/res282": {
      PUT: route({
        before: [authGuard, adminGuard],
        handler: () => json(200, { ok: true, idx: 282 }),
      }),
    },
    "/res285": {
      GET: route({
        before: [authGuard, adminGuard],
        handler: () => json(200, { ok: true, idx: 285 }),
      }),
    },
    "/res288": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 288 }),
      }),
    },
    "/res291": {
      PATCH: route({
        body: z.object({ name291: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 291 }),
      }),
    },
    "/res294": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 294 }),
      }),
    },
    "/res297/:id297": {
      DELETE: route({
        before: [authGuard],
        params: z.object({ id297: z.coerce.number() }),
        body: z.object({ name297: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 297 }),
      }),
    },
    "/res300": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 300 }),
      }),
    },
    "/res303/:id303": {
      PATCH: route({
        params: z.object({ id303: z.coerce.number() }),
        body: z.object({ name303: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 303 }),
      }),
    },
    "/res306": {
      POST: route({
        before: [authGuard, adminGuard],
        handler: () => json(201, { ok: true, idx: 306 }),
      }),
    },
    "/res309": new Response("raw 309"),
    "/res312/:id312": {
      GET: route({
        params: z.object({ id312: z.coerce.number() }),
        query: z.object({ page312: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 312 }),
      }),
    },
    "/res315/:id315": {
      GET: route({
        params: z.object({ id315: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 315 }),
      }),
    },
    "/res318/:id318": new Response("raw 318"),
    "/res321": {
      GET: route({
        query: z.object({ page321: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 321 }),
      }),
    },
    "/res324": {
      PUT: route({
        before: [authGuard],
        body: z.object({ name324: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 324 }),
      }),
    },
    "/res327": new Response("raw 327"),
    "/res330/:id330": {
      PATCH: route({
        params: z.object({ id330: z.coerce.number() }),
        body: z.object({ name330: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 330 }),
      }),
    },
    "/res333/:id333": {
      GET: route({
        params: z.object({ id333: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 333 }),
      }),
    },
    "/res336/:id336": {
      DELETE: route({
        params: z.object({ id336: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 336 }),
      }),
    },
    "/res339": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 339 }),
      }),
    },
    "/res342/:id342": {
      PATCH: route({
        params: z.object({ id342: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 342 }),
      }),
    },
    "/res345": {
      DELETE: route({
        body: z.object({ name345: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 345 }),
      }),
    },
    "/res348": {
      PATCH: route({
        before: [authGuard, adminGuard],
        body: z.object({ name348: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 348 }),
      }),
    },
    "/res351/:id351": {
      PUT: route({
        params: z.object({ id351: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 351 }),
      }),
    },
    "/res354/:id354": {
      GET: route({
        params: z.object({ id354: z.coerce.number() }),
        query: z.object({ page354: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 354 }),
      }),
    },
    "/res357": {
      GET: route({
        handler: () => json(200, { ok: true, idx: 357 }),
      }),
    },
    "/res360/:id360": {
      GET: route({
        params: z.object({ id360: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 360 }),
      }),
    },
    "/res363/:id363": new Response("raw 363"),
    "/res366/:id366": {
      PATCH: route({
        params: z.object({ id366: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 366 }),
      }),
    },
    "/res369": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 369 }),
      }),
    },
    "/res372": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 372 }),
      }),
    },
    "/res375": {
      GET: route({
        before: [authGuard, adminGuard],
        handler: () => json(200, { ok: true, idx: 375 }),
      }),
    },
    "/res378": new Response("raw 378"),
    "/res381": new Response("raw 381"),
    "/res384/:id384": {
      POST: route({
        params: z.object({ id384: z.coerce.number() }),
        body: z.object({ name384: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 384 }),
      }),
    },
    "/res387": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 387 }),
      }),
    },
    "/res390": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 390 }),
      }),
    },
    "/res393/:id393": {
      GET: route({
        params: z.object({ id393: z.coerce.number() }),
        query: z.object({ page393: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 393 }),
      }),
    },
    "/res396/:id396": {
      DELETE: route({
        params: z.object({ id396: z.coerce.number() }),
        body: z.object({ name396: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 396 }),
      }),
    },
    "/res399": {
      PATCH: route({
        body: z.object({ name399: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 399 }),
      }),
    },
    "/res402/:id402": {
      POST: route({
        params: z.object({ id402: z.coerce.number() }),
        handler: () => json(201, { ok: true, idx: 402 }),
      }),
    },
    "/res405/:id405": new Response("raw 405"),
    "/res408/:id408": {
      GET: route({
        params: z.object({ id408: z.coerce.number() }),
        query: z.object({ page408: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 408 }),
      }),
    },
    "/res411": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 411 }),
      }),
    },
    "/res414/:id414": {
      POST: route({
        params: z.object({ id414: z.coerce.number() }),
        body: z.object({ name414: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 414 }),
      }),
    },
    "/res417": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 417 }),
      }),
    },
    "/res420": {
      POST: route({
        body: z.object({ name420: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 420 }),
      }),
    },
    "/res423": new Response("raw 423"),
    "/res426/:id426": {
      PUT: route({
        params: z.object({ id426: z.coerce.number() }),
        body: z.object({ name426: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 426 }),
      }),
    },
    "/res429/:id429": {
      PUT: route({
        before: [authGuard, adminGuard],
        params: z.object({ id429: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 429 }),
      }),
    },
    "/res432": {
      GET: route({
        query: z.object({ page432: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 432 }),
      }),
    },
    "/res435/:id435": {
      DELETE: route({
        before: [authGuard],
        params: z.object({ id435: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 435 }),
      }),
    },
    "/res438": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 438 }),
      }),
    },
    "/res441/:id441": {
      POST: route({
        params: z.object({ id441: z.coerce.number() }),
        body: z.object({ name441: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 441 }),
      }),
    },
    "/res444": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 444 }),
      }),
    },
    "/res447": {
      PUT: route({
        before: [authGuard, adminGuard],
        body: z.object({ name447: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 447 }),
      }),
    },
    "/res450": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 450 }),
      }),
    },
    "/res453/:id453": {
      DELETE: route({
        params: z.object({ id453: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 453 }),
      }),
    },
    "/res456": {
      GET: route({
        handler: () => json(200, { ok: true, idx: 456 }),
      }),
    },
    "/res459/:id459": {
      DELETE: route({
        before: [authGuard],
        params: z.object({ id459: z.coerce.number() }),
        body: z.object({ name459: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 459 }),
      }),
    },
    "/res462": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 462 }),
      }),
    },
    "/res465": {
      PATCH: route({
        body: z.object({ name465: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 465 }),
      }),
    },
    "/res468/:id468": {
      PUT: route({
        params: z.object({ id468: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 468 }),
      }),
    },
    "/res471": {
      GET: route({
        query: z.object({ page471: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 471 }),
      }),
    },
    "/res474": {
      PATCH: route({
        before: [authGuard, adminGuard],
        body: z.object({ name474: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 474 }),
      }),
    },
    "/res477": {
      DELETE: route({
        before: [authGuard, adminGuard],
        handler: () => json(200, { ok: true, idx: 477 }),
      }),
    },
    "/res480": {
      PATCH: route({
        before: [authGuard, adminGuard],
        handler: () => json(200, { ok: true, idx: 480 }),
      }),
    },
    "/res483": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 483 }),
      }),
    },
    "/res486": {
      POST: route({
        before: [authGuard, adminGuard],
        body: z.object({ name486: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 486 }),
      }),
    },
    "/res489": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 489 }),
      }),
    },
    "/res492": {
      PUT: route({
        body: z.object({ name492: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 492 }),
      }),
    },
    "/res495": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 495 }),
      }),
    },
    "/res498": new Response("raw 498"),
  },
});

export const app = defineApp({
  routes: {
    "/res1/:id1": {
      PATCH: route({
        params: z.object({ id1: z.coerce.number() }),
        body: z.object({ name1: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 1 }),
      }),
    },
    "/res2/:id2": {
      PATCH: route({
        params: z.object({ id2: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 2 }),
      }),
    },
    "/res4": {
      GET: route({
        query: z.object({ page4: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 4 }),
      }),
    },
    "/res5/:id5": {
      POST: route({
        params: z.object({ id5: z.coerce.number() }),
        body: z.object({ name5: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 5 }),
      }),
    },
    "/res7": new Response("raw 7"),
    "/res8/:id8": {
      POST: route({
        params: z.object({ id8: z.coerce.number() }),
        body: z.object({ name8: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 8 }),
      }),
    },
    "/res10": {
      POST: route({
        body: z.object({ name10: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 10 }),
      }),
    },
    "/res11/:id11": {
      POST: route({
        params: z.object({ id11: z.coerce.number() }),
        body: z.object({ name11: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 11 }),
      }),
    },
    "/res13": {
      PATCH: route({
        body: z.object({ name13: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 13 }),
      }),
    },
    "/res14/:id14": new Response("raw 14"),
    "/res16/:id16": {
      DELETE: route({
        params: z.object({ id16: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 16 }),
      }),
    },
    "/res17/:id17": {
      PATCH: route({
        before: [authGuard],
        params: z.object({ id17: z.coerce.number() }),
        body: z.object({ name17: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 17 }),
      }),
    },
    "/res19/:id19": {
      DELETE: route({
        params: z.object({ id19: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 19 }),
      }),
    },
    "/res20": {
      POST: route({
        before: [authGuard],
        body: z.object({ name20: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 20 }),
      }),
    },
    "/res22/:id22": {
      POST: route({
        params: z.object({ id22: z.coerce.number() }),
        body: z.object({ name22: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 22 }),
      }),
    },
    "/res23": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 23 }),
      }),
    },
    "/res25": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 25 }),
      }),
    },
    "/res26": {
      PATCH: route({
        body: z.object({ name26: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 26 }),
      }),
    },
    "/res28/:id28": {
      GET: route({
        params: z.object({ id28: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 28 }),
      }),
    },
    "/res29/:id29": {
      PATCH: route({
        before: [authGuard],
        params: z.object({ id29: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 29 }),
      }),
    },
    "/res31": {
      POST: route({
        body: z.object({ name31: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 31 }),
      }),
    },
    "/res32": {
      DELETE: route({
        before: [authGuard],
        body: z.object({ name32: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 32 }),
      }),
    },
    "/res34": {
      GET: route({
        before: [authGuard, adminGuard],
        query: z.object({ page34: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 34 }),
      }),
    },
    "/res35/:id35": {
      PATCH: route({
        params: z.object({ id35: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 35 }),
      }),
    },
    "/res37/:id37": {
      PATCH: route({
        params: z.object({ id37: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 37 }),
      }),
    },
    "/res38/:id38": {
      GET: route({
        params: z.object({ id38: z.coerce.number() }),
        query: z.object({ page38: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 38 }),
      }),
    },
    "/res40": {
      PUT: route({
        before: [authGuard, adminGuard],
        body: z.object({ name40: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 40 }),
      }),
    },
    "/res41": {
      DELETE: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 41 }),
      }),
    },
    "/res43": {
      DELETE: route({
        before: [authGuard, adminGuard],
        handler: () => json(200, { ok: true, idx: 43 }),
      }),
    },
    "/res44": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 44 }),
      }),
    },
    "/res46/:id46": {
      GET: route({
        before: [authGuard],
        params: z.object({ id46: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 46 }),
      }),
    },
    "/res47/:id47": {
      POST: route({
        params: z.object({ id47: z.coerce.number() }),
        handler: () => json(201, { ok: true, idx: 47 }),
      }),
    },
    "/res49": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 49 }),
      }),
    },
    "/res50": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 50 }),
      }),
    },
    "/res52": {
      GET: route({
        query: z.object({ page52: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 52 }),
      }),
    },
    "/res53/:id53": {
      PUT: route({
        params: z.object({ id53: z.coerce.number() }),
        body: z.object({ name53: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 53 }),
      }),
    },
    "/res55": new Response("raw 55"),
    "/res56/:id56": {
      DELETE: route({
        params: z.object({ id56: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 56 }),
      }),
    },
    "/res58": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 58 }),
      }),
    },
    "/res59/:id59": {
      PATCH: route({
        params: z.object({ id59: z.coerce.number() }),
        body: z.object({ name59: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 59 }),
      }),
    },
    "/res61": {
      PATCH: route({
        body: z.object({ name61: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 61 }),
      }),
    },
    "/res62/:id62": {
      PUT: route({
        params: z.object({ id62: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 62 }),
      }),
    },
    "/res64": {
      DELETE: route({
        body: z.object({ name64: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 64 }),
      }),
    },
    "/res65": {
      POST: route({
        body: z.object({ name65: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 65 }),
      }),
    },
    "/res67/:id67": {
      DELETE: route({
        params: z.object({ id67: z.coerce.number() }),
        body: z.object({ name67: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 67 }),
      }),
    },
    "/res68": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 68 }),
      }),
    },
    "/res70": new Response("raw 70"),
    "/res71": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 71 }),
      }),
    },
    "/res73": {
      DELETE: route({
        body: z.object({ name73: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 73 }),
      }),
    },
    "/res74/:id74": {
      DELETE: route({
        params: z.object({ id74: z.coerce.number() }),
        body: z.object({ name74: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 74 }),
      }),
    },
    "/res76/:id76": {
      PATCH: route({
        params: z.object({ id76: z.coerce.number() }),
        body: z.object({ name76: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 76 }),
      }),
    },
    "/res77/:id77": {
      PUT: route({
        params: z.object({ id77: z.coerce.number() }),
        body: z.object({ name77: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 77 }),
      }),
    },
    "/res79": {
      PATCH: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 79 }),
      }),
    },
    "/res80/:id80": {
      GET: route({
        params: z.object({ id80: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 80 }),
      }),
    },
    "/res82": {
      POST: route({
        body: z.object({ name82: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 82 }),
      }),
    },
    "/res83": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 83 }),
      }),
    },
    "/res85": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 85 }),
      }),
    },
    "/res86": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 86 }),
      }),
    },
    "/res88": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 88 }),
      }),
    },
    "/res89": {
      PATCH: route({
        before: [authGuard, adminGuard],
        body: z.object({ name89: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 89 }),
      }),
    },
    "/res91/:id91": {
      POST: route({
        params: z.object({ id91: z.coerce.number() }),
        handler: () => json(201, { ok: true, idx: 91 }),
      }),
    },
    "/res92/:id92": new Response("raw 92"),
    "/res94": {
      POST: route({
        body: z.object({ name94: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 94 }),
      }),
    },
    "/res95/:id95": {
      PUT: route({
        before: [authGuard, adminGuard],
        params: z.object({ id95: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 95 }),
      }),
    },
    "/res97/:id97": {
      GET: route({
        before: [authGuard],
        params: z.object({ id97: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 97 }),
      }),
    },
    "/res98": {
      POST: route({
        body: z.object({ name98: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 98 }),
      }),
    },
    "/res100/:id100": new Response("raw 100"),
    "/res101/:id101": {
      PATCH: route({
        params: z.object({ id101: z.coerce.number() }),
        body: z.object({ name101: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 101 }),
      }),
    },
    "/res103": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 103 }),
      }),
    },
    "/res104": {
      DELETE: route({
        before: [authGuard, adminGuard],
        body: z.object({ name104: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 104 }),
      }),
    },
    "/res106": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 106 }),
      }),
    },
    "/res107/:id107": {
      PATCH: route({
        before: [authGuard, adminGuard],
        params: z.object({ id107: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 107 }),
      }),
    },
    "/res109/:id109": {
      POST: route({
        params: z.object({ id109: z.coerce.number() }),
        handler: () => json(201, { ok: true, idx: 109 }),
      }),
    },
    "/res110/:id110": {
      PUT: route({
        params: z.object({ id110: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 110 }),
      }),
    },
    "/res112": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 112 }),
      }),
    },
    "/res113/:id113": {
      DELETE: route({
        params: z.object({ id113: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 113 }),
      }),
    },
    "/res115": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 115 }),
      }),
    },
    "/res116": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 116 }),
      }),
    },
    "/res118/:id118": {
      PUT: route({
        params: z.object({ id118: z.coerce.number() }),
        body: z.object({ name118: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 118 }),
      }),
    },
    "/res119": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 119 }),
      }),
    },
    "/res121": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 121 }),
      }),
    },
    "/res122/:id122": new Response("raw 122"),
    "/res124/:id124": {
      PUT: route({
        params: z.object({ id124: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 124 }),
      }),
    },
    "/res125": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 125 }),
      }),
    },
    "/res127": {
      PUT: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 127 }),
      }),
    },
    "/res128": {
      PATCH: route({
        before: [authGuard, adminGuard],
        handler: () => json(200, { ok: true, idx: 128 }),
      }),
    },
    "/res130": {
      PUT: route({
        before: [authGuard],
        body: z.object({ name130: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 130 }),
      }),
    },
    "/res131/:id131": {
      PUT: route({
        params: z.object({ id131: z.coerce.number() }),
        body: z.object({ name131: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 131 }),
      }),
    },
    "/res133": {
      DELETE: route({
        before: [authGuard, adminGuard],
        handler: () => json(200, { ok: true, idx: 133 }),
      }),
    },
    "/res134": {
      PUT: route({
        body: z.object({ name134: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 134 }),
      }),
    },
    "/res136": {
      GET: route({
        query: z.object({ page136: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 136 }),
      }),
    },
    "/res137": {
      GET: route({
        before: [authGuard, adminGuard],
        handler: () => json(200, { ok: true, idx: 137 }),
      }),
    },
    "/res139/:id139": {
      PATCH: route({
        params: z.object({ id139: z.coerce.number() }),
        body: z.object({ name139: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 139 }),
      }),
    },
    "/res140/:id140": {
      PATCH: route({
        before: [authGuard],
        params: z.object({ id140: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 140 }),
      }),
    },
    "/res142": {
      PATCH: route({
        body: z.object({ name142: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 142 }),
      }),
    },
    "/res143": {
      GET: route({
        query: z.object({ page143: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 143 }),
      }),
    },
    "/res145": {
      POST: route({
        before: [authGuard],
        body: z.object({ name145: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 145 }),
      }),
    },
    "/res146": {
      POST: route({
        body: z.object({ name146: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 146 }),
      }),
    },
    "/res148": {
      DELETE: route({
        body: z.object({ name148: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 148 }),
      }),
    },
    "/res149": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 149 }),
      }),
    },
    "/res151/:id151": {
      PATCH: route({
        before: [authGuard, adminGuard],
        params: z.object({ id151: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 151 }),
      }),
    },
    "/res152": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 152 }),
      }),
    },
    "/res154/:id154": {
      DELETE: route({
        before: [authGuard],
        params: z.object({ id154: z.coerce.number() }),
        body: z.object({ name154: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 154 }),
      }),
    },
    "/res155/:id155": {
      GET: route({
        params: z.object({ id155: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 155 }),
      }),
    },
    "/res157": new Response("raw 157"),
    "/res158": {
      GET: route({
        query: z.object({ page158: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 158 }),
      }),
    },
    "/res160": {
      DELETE: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 160 }),
      }),
    },
    "/res161/:id161": new Response("raw 161"),
    "/res163/:id163": {
      PATCH: route({
        before: [authGuard],
        params: z.object({ id163: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 163 }),
      }),
    },
    "/res164/:id164": {
      GET: route({
        params: z.object({ id164: z.coerce.number() }),
        query: z.object({ page164: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 164 }),
      }),
    },
    "/res166": new Response("raw 166"),
    "/res167/:id167": {
      PATCH: route({
        params: z.object({ id167: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 167 }),
      }),
    },
    "/res169/:id169": {
      PATCH: route({
        params: z.object({ id169: z.coerce.number() }),
        body: z.object({ name169: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 169 }),
      }),
    },
    "/res170": {
      DELETE: route({
        body: z.object({ name170: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 170 }),
      }),
    },
    "/res172/:id172": {
      POST: route({
        params: z.object({ id172: z.coerce.number() }),
        handler: () => json(201, { ok: true, idx: 172 }),
      }),
    },
    "/res173/:id173": {
      PATCH: route({
        params: z.object({ id173: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 173 }),
      }),
    },
    "/res175": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 175 }),
      }),
    },
    "/res176": {
      POST: route({
        body: z.object({ name176: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 176 }),
      }),
    },
    "/res178": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 178 }),
      }),
    },
    "/res179/:id179": {
      PUT: route({
        before: [authGuard, adminGuard],
        params: z.object({ id179: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 179 }),
      }),
    },
    "/res181": {
      PUT: route({
        body: z.object({ name181: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 181 }),
      }),
    },
    "/res182/:id182": {
      PATCH: route({
        params: z.object({ id182: z.coerce.number() }),
        body: z.object({ name182: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 182 }),
      }),
    },
    "/res184": {
      PUT: route({
        before: [authGuard, adminGuard],
        body: z.object({ name184: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 184 }),
      }),
    },
    "/res185": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 185 }),
      }),
    },
    "/res187/:id187": {
      DELETE: route({
        params: z.object({ id187: z.coerce.number() }),
        body: z.object({ name187: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 187 }),
      }),
    },
    "/res188/:id188": {
      POST: route({
        before: [authGuard, adminGuard],
        params: z.object({ id188: z.coerce.number() }),
        handler: () => json(201, { ok: true, idx: 188 }),
      }),
    },
    "/res190/:id190": {
      POST: route({
        params: z.object({ id190: z.coerce.number() }),
        body: z.object({ name190: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 190 }),
      }),
    },
    "/res191": {
      PATCH: route({
        before: [authGuard],
        body: z.object({ name191: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 191 }),
      }),
    },
    "/res193": {
      PATCH: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 193 }),
      }),
    },
    "/res194": {
      PUT: route({
        body: z.object({ name194: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 194 }),
      }),
    },
    "/res196": {
      GET: route({
        before: [authGuard, adminGuard],
        query: z.object({ page196: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 196 }),
      }),
    },
    "/res197": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 197 }),
      }),
    },
    "/res199": {
      POST: route({
        before: [authGuard, adminGuard],
        handler: () => json(201, { ok: true, idx: 199 }),
      }),
    },
    "/res200": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 200 }),
      }),
    },
    "/res202": {
      PUT: route({
        body: z.object({ name202: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 202 }),
      }),
    },
    "/res203": {
      DELETE: route({
        body: z.object({ name203: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 203 }),
      }),
    },
    "/res205/:id205": {
      GET: route({
        params: z.object({ id205: z.coerce.number() }),
        query: z.object({ page205: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 205 }),
      }),
    },
    "/res206": {
      PUT: route({
        before: [authGuard],
        body: z.object({ name206: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 206 }),
      }),
    },
    "/res208": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 208 }),
      }),
    },
    "/res209/:id209": {
      PUT: route({
        params: z.object({ id209: z.coerce.number() }),
        body: z.object({ name209: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 209 }),
      }),
    },
    "/res211": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 211 }),
      }),
    },
    "/res212": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 212 }),
      }),
    },
    "/res214": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 214 }),
      }),
    },
    "/res215": {
      POST: route({
        before: [authGuard, adminGuard],
        body: z.object({ name215: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 215 }),
      }),
    },
    "/res217": {
      DELETE: route({
        body: z.object({ name217: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 217 }),
      }),
    },
    "/res218/:id218": {
      DELETE: route({
        params: z.object({ id218: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 218 }),
      }),
    },
    "/res220/:id220": {
      DELETE: route({
        params: z.object({ id220: z.coerce.number() }),
        body: z.object({ name220: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 220 }),
      }),
    },
    "/res221": {
      PATCH: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 221 }),
      }),
    },
    "/res223": {
      PATCH: route({
        before: [authGuard, adminGuard],
        handler: () => json(200, { ok: true, idx: 223 }),
      }),
    },
    "/res224/:id224": {
      GET: route({
        params: z.object({ id224: z.coerce.number() }),
        query: z.object({ page224: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 224 }),
      }),
    },
    "/res226": {
      PATCH: route({
        before: [authGuard, adminGuard],
        handler: () => json(200, { ok: true, idx: 226 }),
      }),
    },
    "/res227/:id227": {
      PATCH: route({
        before: [authGuard],
        params: z.object({ id227: z.coerce.number() }),
        body: z.object({ name227: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 227 }),
      }),
    },
    "/res229/:id229": new Response("raw 229"),
    "/res230/:id230": {
      POST: route({
        before: [authGuard],
        params: z.object({ id230: z.coerce.number() }),
        handler: () => json(201, { ok: true, idx: 230 }),
      }),
    },
    "/res232": {
      PATCH: route({
        body: z.object({ name232: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 232 }),
      }),
    },
    "/res233": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 233 }),
      }),
    },
    "/res235": new Response("raw 235"),
    "/res236/:id236": {
      GET: route({
        params: z.object({ id236: z.coerce.number() }),
        query: z.object({ page236: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 236 }),
      }),
    },
    "/res238/:id238": new Response("raw 238"),
    "/res239": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 239 }),
      }),
    },
    "/res241": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 241 }),
      }),
    },
    "/res242": {
      PATCH: route({
        body: z.object({ name242: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 242 }),
      }),
    },
    "/res244": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 244 }),
      }),
    },
    "/res245": {
      PATCH: route({
        before: [authGuard, adminGuard],
        body: z.object({ name245: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 245 }),
      }),
    },
    "/res247": {
      DELETE: route({
        body: z.object({ name247: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 247 }),
      }),
    },
    "/res248": new Response("raw 248"),
    "/res250": {
      PATCH: route({
        body: z.object({ name250: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 250 }),
      }),
    },
    "/res251/:id251": {
      PATCH: route({
        params: z.object({ id251: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 251 }),
      }),
    },
    "/res253/:id253": new Response("raw 253"),
    "/res254": {
      PUT: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 254 }),
      }),
    },
    "/res256/:id256": {
      POST: route({
        before: [authGuard, adminGuard],
        params: z.object({ id256: z.coerce.number() }),
        body: z.object({ name256: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 256 }),
      }),
    },
    "/res257": {
      DELETE: route({
        before: [authGuard],
        body: z.object({ name257: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 257 }),
      }),
    },
    "/res259": {
      PUT: route({
        body: z.object({ name259: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 259 }),
      }),
    },
    "/res260": {
      GET: route({
        before: [authGuard, adminGuard],
        query: z.object({ page260: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 260 }),
      }),
    },
    "/res262/:id262": {
      PUT: route({
        params: z.object({ id262: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 262 }),
      }),
    },
    "/res263": {
      DELETE: route({
        body: z.object({ name263: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 263 }),
      }),
    },
    "/res265": {
      DELETE: route({
        body: z.object({ name265: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 265 }),
      }),
    },
    "/res266/:id266": {
      PATCH: route({
        params: z.object({ id266: z.coerce.number() }),
        body: z.object({ name266: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 266 }),
      }),
    },
    "/res268": {
      PUT: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 268 }),
      }),
    },
    "/res269": {
      PATCH: route({
        body: z.object({ name269: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 269 }),
      }),
    },
    "/res271": {
      GET: route({
        handler: () => json(200, { ok: true, idx: 271 }),
      }),
    },
    "/res272": {
      DELETE: route({
        body: z.object({ name272: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 272 }),
      }),
    },
    "/res274/:id274": {
      PATCH: route({
        before: [authGuard],
        params: z.object({ id274: z.coerce.number() }),
        body: z.object({ name274: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 274 }),
      }),
    },
    "/res275/:id275": {
      GET: route({
        params: z.object({ id275: z.coerce.number() }),
        query: z.object({ page275: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 275 }),
      }),
    },
    "/res277": {
      GET: route({
        query: z.object({ page277: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 277 }),
      }),
    },
    "/res278": {
      PATCH: route({
        before: [authGuard, adminGuard],
        body: z.object({ name278: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 278 }),
      }),
    },
    "/res280": new Response("raw 280"),
    "/res281/:id281": {
      DELETE: route({
        params: z.object({ id281: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 281 }),
      }),
    },
    "/res283": {
      PATCH: route({
        body: z.object({ name283: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 283 }),
      }),
    },
    "/res284": {
      PUT: route({
        before: [authGuard, adminGuard],
        handler: () => json(200, { ok: true, idx: 284 }),
      }),
    },
    "/res286": {
      POST: route({
        before: [authGuard],
        body: z.object({ name286: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 286 }),
      }),
    },
    "/res287/:id287": {
      PATCH: route({
        before: [authGuard, adminGuard],
        params: z.object({ id287: z.coerce.number() }),
        body: z.object({ name287: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 287 }),
      }),
    },
    "/res289": {
      PATCH: route({
        body: z.object({ name289: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 289 }),
      }),
    },
    "/res290": {
      GET: route({
        before: [authGuard],
        query: z.object({ page290: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 290 }),
      }),
    },
    "/res292/:id292": {
      PATCH: route({
        params: z.object({ id292: z.coerce.number() }),
        body: z.object({ name292: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 292 }),
      }),
    },
    "/res293/:id293": new Response("raw 293"),
    "/res295": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 295 }),
      }),
    },
    "/res296/:id296": {
      PUT: route({
        params: z.object({ id296: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 296 }),
      }),
    },
    "/res298": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 298 }),
      }),
    },
    "/res299/:id299": {
      DELETE: route({
        params: z.object({ id299: z.coerce.number() }),
        body: z.object({ name299: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 299 }),
      }),
    },
    "/res301": {
      PUT: route({
        before: [authGuard, adminGuard],
        body: z.object({ name301: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 301 }),
      }),
    },
    "/res302": {
      GET: route({
        query: z.object({ page302: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 302 }),
      }),
    },
    "/res304/:id304": {
      GET: route({
        params: z.object({ id304: z.coerce.number() }),
        query: z.object({ page304: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 304 }),
      }),
    },
    "/res305": new Response("raw 305"),
    "/res307/:id307": {
      PATCH: route({
        params: z.object({ id307: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 307 }),
      }),
    },
    "/res308": {
      PATCH: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 308 }),
      }),
    },
    "/res310": {
      PATCH: route({
        body: z.object({ name310: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 310 }),
      }),
    },
    "/res311/:id311": {
      PUT: route({
        params: z.object({ id311: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 311 }),
      }),
    },
    "/res313": {
      PUT: route({
        body: z.object({ name313: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 313 }),
      }),
    },
    "/res314": {
      PUT: route({
        body: z.object({ name314: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 314 }),
      }),
    },
    "/res316": {
      DELETE: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 316 }),
      }),
    },
    "/res317": {
      PUT: route({
        body: z.object({ name317: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 317 }),
      }),
    },
    "/res319": new Response("raw 319"),
    "/res320": {
      PUT: route({
        body: z.object({ name320: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 320 }),
      }),
    },
    "/res322": {
      PUT: route({
        body: z.object({ name322: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 322 }),
      }),
    },
    "/res323/:id323": new Response("raw 323"),
    "/res325/:id325": new Response("raw 325"),
    "/res326/:id326": {
      GET: route({
        before: [authGuard],
        params: z.object({ id326: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 326 }),
      }),
    },
    "/res328": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 328 }),
      }),
    },
    "/res329": {
      DELETE: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 329 }),
      }),
    },
    "/res331": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 331 }),
      }),
    },
    "/res332": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 332 }),
      }),
    },
    "/res334/:id334": {
      POST: route({
        before: [authGuard],
        params: z.object({ id334: z.coerce.number() }),
        body: z.object({ name334: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 334 }),
      }),
    },
    "/res335": {
      PATCH: route({
        body: z.object({ name335: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 335 }),
      }),
    },
    "/res337/:id337": {
      PATCH: route({
        params: z.object({ id337: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 337 }),
      }),
    },
    "/res338": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 338 }),
      }),
    },
    "/res340/:id340": {
      PATCH: route({
        before: [authGuard, adminGuard],
        params: z.object({ id340: z.coerce.number() }),
        body: z.object({ name340: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 340 }),
      }),
    },
    "/res341": {
      DELETE: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 341 }),
      }),
    },
    "/res343/:id343": {
      DELETE: route({
        params: z.object({ id343: z.coerce.number() }),
        body: z.object({ name343: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 343 }),
      }),
    },
    "/res344/:id344": {
      PATCH: route({
        params: z.object({ id344: z.coerce.number() }),
        body: z.object({ name344: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 344 }),
      }),
    },
    "/res346": {
      GET: route({
        before: [authGuard],
        query: z.object({ page346: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 346 }),
      }),
    },
    "/res347/:id347": {
      GET: route({
        before: [authGuard, adminGuard],
        params: z.object({ id347: z.coerce.number() }),
        query: z.object({ page347: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 347 }),
      }),
    },
    "/res349/:id349": {
      DELETE: route({
        before: [authGuard],
        params: z.object({ id349: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 349 }),
      }),
    },
    "/res350": {
      GET: route({
        query: z.object({ page350: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 350 }),
      }),
    },
    "/res352": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 352 }),
      }),
    },
    "/res353/:id353": {
      PATCH: route({
        params: z.object({ id353: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 353 }),
      }),
    },
    "/res355": {
      GET: route({
        handler: () => json(200, { ok: true, idx: 355 }),
      }),
    },
    "/res356/:id356": {
      DELETE: route({
        params: z.object({ id356: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 356 }),
      }),
    },
    "/res358/:id358": {
      GET: route({
        params: z.object({ id358: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 358 }),
      }),
    },
    "/res359": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 359 }),
      }),
    },
    "/res361/:id361": {
      POST: route({
        params: z.object({ id361: z.coerce.number() }),
        body: z.object({ name361: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 361 }),
      }),
    },
    "/res362": {
      POST: route({
        before: [authGuard],
        body: z.object({ name362: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 362 }),
      }),
    },
    "/res364": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 364 }),
      }),
    },
    "/res365": {
      GET: route({
        query: z.object({ page365: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 365 }),
      }),
    },
    "/res367": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 367 }),
      }),
    },
    "/res368": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 368 }),
      }),
    },
    "/res370/:id370": new Response("raw 370"),
    "/res371/:id371": {
      DELETE: route({
        params: z.object({ id371: z.coerce.number() }),
        body: z.object({ name371: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 371 }),
      }),
    },
    "/res373/:id373": {
      PUT: route({
        params: z.object({ id373: z.coerce.number() }),
        body: z.object({ name373: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 373 }),
      }),
    },
    "/res374": {
      DELETE: route({
        before: [authGuard],
        body: z.object({ name374: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 374 }),
      }),
    },
    "/res376": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 376 }),
      }),
    },
    "/res377/:id377": {
      DELETE: route({
        params: z.object({ id377: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 377 }),
      }),
    },
    "/res379": {
      PUT: route({
        body: z.object({ name379: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 379 }),
      }),
    },
    "/res380": {
      GET: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 380 }),
      }),
    },
    "/res382/:id382": {
      DELETE: route({
        before: [authGuard],
        params: z.object({ id382: z.coerce.number() }),
        body: z.object({ name382: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 382 }),
      }),
    },
    "/res383/:id383": {
      GET: route({
        params: z.object({ id383: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 383 }),
      }),
    },
    "/res385/:id385": {
      PATCH: route({
        params: z.object({ id385: z.coerce.number() }),
        body: z.object({ name385: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 385 }),
      }),
    },
    "/res386": {
      PUT: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 386 }),
      }),
    },
    "/res388/:id388": {
      PUT: route({
        params: z.object({ id388: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 388 }),
      }),
    },
    "/res389/:id389": {
      PUT: route({
        params: z.object({ id389: z.coerce.number() }),
        body: z.object({ name389: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 389 }),
      }),
    },
    "/res391/:id391": {
      PATCH: route({
        params: z.object({ id391: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 391 }),
      }),
    },
    "/res392/:id392": {
      PUT: route({
        params: z.object({ id392: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 392 }),
      }),
    },
    "/res394": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 394 }),
      }),
    },
    "/res395/:id395": {
      PATCH: route({
        params: z.object({ id395: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 395 }),
      }),
    },
    "/res397": {
      PUT: route({
        before: [authGuard, adminGuard],
        handler: () => json(200, { ok: true, idx: 397 }),
      }),
    },
    "/res398/:id398": {
      PUT: route({
        params: z.object({ id398: z.coerce.number() }),
        body: z.object({ name398: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 398 }),
      }),
    },
    "/res400": {
      GET: route({
        query: z.object({ page400: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 400 }),
      }),
    },
    "/res401/:id401": {
      DELETE: route({
        params: z.object({ id401: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 401 }),
      }),
    },
    "/res403": new Response("raw 403"),
    "/res404/:id404": new Response("raw 404"),
    "/res406": new Response("raw 406"),
    "/res407": {
      POST: route({
        before: [authGuard, adminGuard],
        body: z.object({ name407: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 407 }),
      }),
    },
    "/res409": {
      POST: route({
        before: [authGuard, adminGuard],
        body: z.object({ name409: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 409 }),
      }),
    },
    "/res410/:id410": {
      PUT: route({
        params: z.object({ id410: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 410 }),
      }),
    },
    "/res412/:id412": {
      DELETE: route({
        params: z.object({ id412: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 412 }),
      }),
    },
    "/res413": {
      POST: route({
        body: z.object({ name413: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 413 }),
      }),
    },
    "/res415": {
      PUT: route({
        before: [authGuard, adminGuard],
        handler: () => json(200, { ok: true, idx: 415 }),
      }),
    },
    "/res416": {
      POST: route({
        body: z.object({ name416: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 416 }),
      }),
    },
    "/res418": {
      DELETE: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 418 }),
      }),
    },
    "/res419": {
      PATCH: route({
        body: z.object({ name419: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 419 }),
      }),
    },
    "/res421": {
      PATCH: route({
        before: [authGuard, adminGuard],
        body: z.object({ name421: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 421 }),
      }),
    },
    "/res422": {
      PATCH: route({
        body: z.object({ name422: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 422 }),
      }),
    },
    "/res424": {
      GET: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 424 }),
      }),
    },
    "/res425/:id425": {
      POST: route({
        params: z.object({ id425: z.coerce.number() }),
        body: z.object({ name425: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 425 }),
      }),
    },
    "/res427": {
      GET: route({
        before: [authGuard],
        query: z.object({ page427: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 427 }),
      }),
    },
    "/res428/:id428": {
      GET: route({
        params: z.object({ id428: z.coerce.number() }),
        query: z.object({ page428: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 428 }),
      }),
    },
    "/res430": {
      DELETE: route({
        body: z.object({ name430: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 430 }),
      }),
    },
    "/res431": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 431 }),
      }),
    },
    "/res433/:id433": {
      GET: route({
        before: [authGuard, adminGuard],
        params: z.object({ id433: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 433 }),
      }),
    },
    "/res434": {
      GET: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 434 }),
      }),
    },
    "/res436": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 436 }),
      }),
    },
    "/res437": {
      PATCH: route({
        body: z.object({ name437: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 437 }),
      }),
    },
    "/res439": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 439 }),
      }),
    },
    "/res440": {
      GET: route({
        before: [authGuard, adminGuard],
        query: z.object({ page440: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 440 }),
      }),
    },
    "/res442/:id442": {
      PATCH: route({
        params: z.object({ id442: z.coerce.number() }),
        body: z.object({ name442: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 442 }),
      }),
    },
    "/res443": {
      GET: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 443 }),
      }),
    },
    "/res445": new Response("raw 445"),
    "/res446/:id446": {
      GET: route({
        params: z.object({ id446: z.coerce.number() }),
        query: z.object({ page446: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 446 }),
      }),
    },
    "/res448/:id448": {
      DELETE: route({
        before: [authGuard, adminGuard],
        params: z.object({ id448: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 448 }),
      }),
    },
    "/res449": {
      GET: route({
        handler: () => json(200, { ok: true, idx: 449 }),
      }),
    },
    "/res451": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 451 }),
      }),
    },
    "/res452": new Response("raw 452"),
    "/res454": {
      POST: route({
        body: z.object({ name454: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 454 }),
      }),
    },
    "/res455": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 455 }),
      }),
    },
    "/res457": new Response("raw 457"),
    "/res458/:id458": {
      PATCH: route({
        before: [authGuard, adminGuard],
        params: z.object({ id458: z.coerce.number() }),
        body: z.object({ name458: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 458 }),
      }),
    },
    "/res460": {
      GET: route({
        query: z.object({ page460: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 460 }),
      }),
    },
    "/res461": {
      DELETE: route({
        before: [authGuard, adminGuard],
        body: z.object({ name461: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 461 }),
      }),
    },
    "/res463/:id463": {
      PATCH: route({
        params: z.object({ id463: z.coerce.number() }),
        body: z.object({ name463: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 463 }),
      }),
    },
    "/res464": {
      GET: route({
        query: z.object({ page464: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 464 }),
      }),
    },
    "/res466": {
      PUT: route({
        before: [authGuard, adminGuard],
        handler: () => json(200, { ok: true, idx: 466 }),
      }),
    },
    "/res467/:id467": {
      DELETE: route({
        params: z.object({ id467: z.coerce.number() }),
        body: z.object({ name467: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 467 }),
      }),
    },
    "/res469": {
      PUT: route({
        before: [authGuard, adminGuard],
        body: z.object({ name469: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 469 }),
      }),
    },
    "/res470": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 470 }),
      }),
    },
    "/res472/:id472": {
      PATCH: route({
        before: [authGuard, adminGuard],
        params: z.object({ id472: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 472 }),
      }),
    },
    "/res473": {
      POST: route({
        body: z.object({ name473: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 473 }),
      }),
    },
    "/res475": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 475 }),
      }),
    },
    "/res476": {
      POST: route({
        before: [authGuard, adminGuard],
        handler: () => json(201, { ok: true, idx: 476 }),
      }),
    },
    "/res478": {
      GET: route({
        handler: () => json(200, { ok: true, idx: 478 }),
      }),
    },
    "/res479/:id479": {
      POST: route({
        params: z.object({ id479: z.coerce.number() }),
        handler: () => json(201, { ok: true, idx: 479 }),
      }),
    },
    "/res481": {
      PATCH: route({
        body: z.object({ name481: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 481 }),
      }),
    },
    "/res482/:id482": {
      GET: route({
        params: z.object({ id482: z.coerce.number() }),
        query: z.object({ page482: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 482 }),
      }),
    },
    "/res484/:id484": {
      PUT: route({
        before: [authGuard, adminGuard],
        params: z.object({ id484: z.coerce.number() }),
        body: z.object({ name484: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 484 }),
      }),
    },
    "/res485": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 485 }),
      }),
    },
    "/res487/:id487": {
      DELETE: route({
        params: z.object({ id487: z.coerce.number() }),
        body: z.object({ name487: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 487 }),
      }),
    },
    "/res488/:id488": {
      DELETE: route({
        params: z.object({ id488: z.coerce.number() }),
        body: z.object({ name488: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 488 }),
      }),
    },
    "/res490/:id490": {
      GET: route({
        params: z.object({ id490: z.coerce.number() }),
        query: z.object({ page490: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 490 }),
      }),
    },
    "/res491/:id491": {
      PUT: route({
        before: [authGuard],
        params: z.object({ id491: z.coerce.number() }),
        body: z.object({ name491: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 491 }),
      }),
    },
    "/res493/:id493": {
      PUT: route({
        params: z.object({ id493: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 493 }),
      }),
    },
    "/res494": {
      GET: route({
        query: z.object({ page494: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 494 }),
      }),
    },
    "/res496": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 496 }),
      }),
    },
    "/res497/:id497": new Response("raw 497"),
    "/res499": {
      GET: route({
        query: z.object({ page499: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 499 }),
      }),
    },
  },
  modules: [featureModule],
});

export default app;