// GENERATED by scripts/generate-type-fixtures.ts (seed 424242) — do not edit by hand.
// target=100 guardDensity=0.25 schemaDensity=0.5
import { z } from "zod";
import { defineApp } from "../../../src/core/app";
import { defineModule } from "../../../src/core/module";
import { route } from "../../../src/core/route";
import { guard } from "../../../src/core/guard";
import { json, text, problem } from "../../../src/core/response";

const authGuard = guard({
  name: "authGuard",
  handler: () => json(401, { error: 'unauthorized' }),
});
const adminGuard = guard({
  name: "adminGuard",
  handler: () => problem(403, { title: 'Forbidden' }),
});

// --- module routes (1/3 of total) ---
const featureModule = defineModule({
  name: "featureModule",
  routes: {
    "/res0": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 0 }),
      }),
    },
    "/res3": {
      GET: route({
        query: z.object({ page3: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 3 }),
      }),
    },
    "/res6": {
      POST: route({
        body: z.object({ name6: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 6 }),
      }),
    },
    "/res9": new Response("raw 9"),
    "/res12": new Response("raw 12"),
    "/res15/:id15": {
      PUT: route({
        params: z.object({ id15: z.coerce.number() }),
        body: z.object({ name15: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 15 }),
      }),
    },
    "/res18": {
      PUT: route({
        body: z.object({ name18: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 18 }),
      }),
    },
    "/res21/:id21": {
      PATCH: route({
        before: [authGuard, adminGuard],
        params: z.object({ id21: z.coerce.number() }),
        body: z.object({ name21: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 21 }),
      }),
    },
    "/res24/:id24": {
      PATCH: route({
        params: z.object({ id24: z.coerce.number() }),
        body: z.object({ name24: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 24 }),
      }),
    },
    "/res27": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 27 }),
      }),
    },
    "/res30": {
      GET: route({
        query: z.object({ page30: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 30 }),
      }),
    },
    "/res33/:id33": {
      PATCH: route({
        params: z.object({ id33: z.coerce.number() }),
        body: z.object({ name33: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 33 }),
      }),
    },
    "/res36": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 36 }),
      }),
    },
    "/res39": new Response("raw 39"),
    "/res42": {
      GET: route({
        handler: () => json(200, { ok: true, idx: 42 }),
      }),
    },
    "/res45/:id45": {
      POST: route({
        params: z.object({ id45: z.coerce.number() }),
        handler: () => json(201, { ok: true, idx: 45 }),
      }),
    },
    "/res48": {
      PUT: route({
        body: z.object({ name48: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 48 }),
      }),
    },
    "/res51/:id51": {
      DELETE: route({
        params: z.object({ id51: z.coerce.number() }),
        body: z.object({ name51: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 51 }),
      }),
    },
    "/res54": new Response("raw 54"),
    "/res57/:id57": {
      DELETE: route({
        params: z.object({ id57: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 57 }),
      }),
    },
    "/res60": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 60 }),
      }),
    },
    "/res63": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 63 }),
      }),
    },
    "/res66/:id66": {
      GET: route({
        params: z.object({ id66: z.coerce.number() }),
        query: z.object({ page66: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 66 }),
      }),
    },
    "/res69": {
      PUT: route({
        body: z.object({ name69: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 69 }),
      }),
    },
    "/res72": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 72 }),
      }),
    },
    "/res75": {
      PATCH: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 75 }),
      }),
    },
    "/res78/:id78": {
      DELETE: route({
        params: z.object({ id78: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 78 }),
      }),
    },
    "/res81": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 81 }),
      }),
    },
    "/res84/:id84": {
      PUT: route({
        params: z.object({ id84: z.coerce.number() }),
        body: z.object({ name84: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 84 }),
      }),
    },
    "/res87/:id87": {
      PUT: route({
        params: z.object({ id87: z.coerce.number() }),
        body: z.object({ name87: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 87 }),
      }),
    },
    "/res90/:id90": {
      DELETE: route({
        params: z.object({ id90: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 90 }),
      }),
    },
    "/res93": {
      POST: route({
        before: [authGuard],
        body: z.object({ name93: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 93 }),
      }),
    },
    "/res96/:id96": {
      PATCH: route({
        params: z.object({ id96: z.coerce.number() }),
        body: z.object({ name96: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 96 }),
      }),
    },
    "/res99": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 99 }),
      }),
    },
  },
});

export const app = defineApp({
  routes: {
    "/res1/:id1": {
      PATCH: route({
        params: z.object({ id1: z.coerce.number() }),
        body: z.object({ name1: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 1 }),
      }),
    },
    "/res2/:id2": {
      PATCH: route({
        params: z.object({ id2: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 2 }),
      }),
    },
    "/res4": {
      GET: route({
        query: z.object({ page4: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 4 }),
      }),
    },
    "/res5/:id5": {
      POST: route({
        params: z.object({ id5: z.coerce.number() }),
        body: z.object({ name5: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 5 }),
      }),
    },
    "/res7": new Response("raw 7"),
    "/res8/:id8": {
      POST: route({
        params: z.object({ id8: z.coerce.number() }),
        body: z.object({ name8: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 8 }),
      }),
    },
    "/res10": {
      POST: route({
        body: z.object({ name10: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 10 }),
      }),
    },
    "/res11/:id11": {
      POST: route({
        params: z.object({ id11: z.coerce.number() }),
        body: z.object({ name11: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 11 }),
      }),
    },
    "/res13": {
      PATCH: route({
        body: z.object({ name13: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 13 }),
      }),
    },
    "/res14/:id14": new Response("raw 14"),
    "/res16/:id16": {
      DELETE: route({
        params: z.object({ id16: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 16 }),
      }),
    },
    "/res17/:id17": {
      PATCH: route({
        before: [authGuard],
        params: z.object({ id17: z.coerce.number() }),
        body: z.object({ name17: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 17 }),
      }),
    },
    "/res19/:id19": {
      DELETE: route({
        params: z.object({ id19: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 19 }),
      }),
    },
    "/res20": {
      POST: route({
        before: [authGuard],
        body: z.object({ name20: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 20 }),
      }),
    },
    "/res22/:id22": {
      POST: route({
        params: z.object({ id22: z.coerce.number() }),
        body: z.object({ name22: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 22 }),
      }),
    },
    "/res23": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 23 }),
      }),
    },
    "/res25": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 25 }),
      }),
    },
    "/res26": {
      PATCH: route({
        body: z.object({ name26: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 26 }),
      }),
    },
    "/res28/:id28": {
      GET: route({
        params: z.object({ id28: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 28 }),
      }),
    },
    "/res29/:id29": {
      PATCH: route({
        before: [authGuard],
        params: z.object({ id29: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 29 }),
      }),
    },
    "/res31": {
      POST: route({
        body: z.object({ name31: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 31 }),
      }),
    },
    "/res32": {
      DELETE: route({
        before: [authGuard],
        body: z.object({ name32: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 32 }),
      }),
    },
    "/res34": {
      GET: route({
        before: [authGuard, adminGuard],
        query: z.object({ page34: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 34 }),
      }),
    },
    "/res35/:id35": {
      PATCH: route({
        params: z.object({ id35: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 35 }),
      }),
    },
    "/res37/:id37": {
      PATCH: route({
        params: z.object({ id37: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 37 }),
      }),
    },
    "/res38/:id38": {
      GET: route({
        params: z.object({ id38: z.coerce.number() }),
        query: z.object({ page38: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 38 }),
      }),
    },
    "/res40": {
      PUT: route({
        before: [authGuard, adminGuard],
        body: z.object({ name40: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 40 }),
      }),
    },
    "/res41": {
      DELETE: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 41 }),
      }),
    },
    "/res43": {
      DELETE: route({
        before: [authGuard, adminGuard],
        handler: () => json(200, { ok: true, idx: 43 }),
      }),
    },
    "/res44": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 44 }),
      }),
    },
    "/res46/:id46": {
      GET: route({
        before: [authGuard],
        params: z.object({ id46: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 46 }),
      }),
    },
    "/res47/:id47": {
      POST: route({
        params: z.object({ id47: z.coerce.number() }),
        handler: () => json(201, { ok: true, idx: 47 }),
      }),
    },
    "/res49": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 49 }),
      }),
    },
    "/res50": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 50 }),
      }),
    },
    "/res52": {
      GET: route({
        query: z.object({ page52: z.coerce.number(), tag: z.string().optional() }),
        handler: () => json(200, { ok: true, idx: 52 }),
      }),
    },
    "/res53/:id53": {
      PUT: route({
        params: z.object({ id53: z.coerce.number() }),
        body: z.object({ name53: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 53 }),
      }),
    },
    "/res55": new Response("raw 55"),
    "/res56/:id56": {
      DELETE: route({
        params: z.object({ id56: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 56 }),
      }),
    },
    "/res58": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 58 }),
      }),
    },
    "/res59/:id59": {
      PATCH: route({
        params: z.object({ id59: z.coerce.number() }),
        body: z.object({ name59: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 59 }),
      }),
    },
    "/res61": {
      PATCH: route({
        body: z.object({ name61: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 61 }),
      }),
    },
    "/res62/:id62": {
      PUT: route({
        params: z.object({ id62: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 62 }),
      }),
    },
    "/res64": {
      DELETE: route({
        body: z.object({ name64: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 64 }),
      }),
    },
    "/res65": {
      POST: route({
        body: z.object({ name65: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 65 }),
      }),
    },
    "/res67/:id67": {
      DELETE: route({
        params: z.object({ id67: z.coerce.number() }),
        body: z.object({ name67: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 67 }),
      }),
    },
    "/res68": {
      PATCH: route({
        handler: () => json(200, { ok: true, idx: 68 }),
      }),
    },
    "/res70": new Response("raw 70"),
    "/res71": {
      PUT: route({
        handler: () => json(200, { ok: true, idx: 71 }),
      }),
    },
    "/res73": {
      DELETE: route({
        body: z.object({ name73: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 73 }),
      }),
    },
    "/res74/:id74": {
      DELETE: route({
        params: z.object({ id74: z.coerce.number() }),
        body: z.object({ name74: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 74 }),
      }),
    },
    "/res76/:id76": {
      PATCH: route({
        params: z.object({ id76: z.coerce.number() }),
        body: z.object({ name76: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 76 }),
      }),
    },
    "/res77/:id77": {
      PUT: route({
        params: z.object({ id77: z.coerce.number() }),
        body: z.object({ name77: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 77 }),
      }),
    },
    "/res79": {
      PATCH: route({
        before: [authGuard],
        handler: () => json(200, { ok: true, idx: 79 }),
      }),
    },
    "/res80/:id80": {
      GET: route({
        params: z.object({ id80: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 80 }),
      }),
    },
    "/res82": {
      POST: route({
        body: z.object({ name82: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 82 }),
      }),
    },
    "/res83": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 83 }),
      }),
    },
    "/res85": {
      DELETE: route({
        handler: () => json(200, { ok: true, idx: 85 }),
      }),
    },
    "/res86": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 86 }),
      }),
    },
    "/res88": {
      POST: route({
        handler: () => json(201, { ok: true, idx: 88 }),
      }),
    },
    "/res89": {
      PATCH: route({
        before: [authGuard, adminGuard],
        body: z.object({ name89: z.string(), count: z.number() }),
        handler: () => json(200, { ok: true, idx: 89 }),
      }),
    },
    "/res91/:id91": {
      POST: route({
        params: z.object({ id91: z.coerce.number() }),
        handler: () => json(201, { ok: true, idx: 91 }),
      }),
    },
    "/res92/:id92": new Response("raw 92"),
    "/res94": {
      POST: route({
        body: z.object({ name94: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 94 }),
      }),
    },
    "/res95/:id95": {
      PUT: route({
        before: [authGuard, adminGuard],
        params: z.object({ id95: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 95 }),
      }),
    },
    "/res97/:id97": {
      GET: route({
        before: [authGuard],
        params: z.object({ id97: z.coerce.number() }),
        handler: () => json(200, { ok: true, idx: 97 }),
      }),
    },
    "/res98": {
      POST: route({
        body: z.object({ name98: z.string(), count: z.number() }),
        handler: () => json(201, { ok: true, idx: 98 }),
      }),
    },
  },
  modules: [featureModule],
});

export default app;