/**
 * GENERATED by scripts/build.ts from the Vite build manifest — do not edit.
 *
 * ASSET_FILES: content-hashed build outputs mapped to explicit long-lived
 * caching (ADR-0037 object form). DIST: the built frontend root used as the
 * SPA shell source. Rebuild with `bun run build` after frontend changes.
 *
 * Paths resolve from the process working directory: the server is started
 * from the starter root via the package scripts (works identically for the
 * source entry and the bundled dist-server entry).
 */
import { resolve } from "node:path";

export const DIST = resolve(process.cwd(), "dist");

export const ASSET_FILES: Readonly<Record<string, { readonly path: string; readonly cacheControl: string }>> = {
  ["/assets/index-Bie9a_TS.js"]: { path: resolve(process.cwd(), "dist/assets/index-Bie9a_TS.js"), cacheControl: "public, max-age=31536000, immutable" },
};
