#!/usr/bin/env bun
/**
 * Deterministic route type fixture generator (M3-005).
 *
 * Generates stress applications at 25 / 100 / 500 / 1,000 routes with
 * realistic contract diversity: mixed methods, path params, query/body
 * schemas, guard chains, typed and raw responses, and module composition.
 * Output is a pure function of the seed (424242) — regeneration is diff-free.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

type GenOptions = {
  readonly target: number;
  readonly guardDensity: number; // 0..1 fraction of routes with guards
  readonly schemaDensity: number; // 0..1 fraction of routes with schemas
};

const SEED = 424242;

/** Deterministic LCG PRNG — same seed, same output. */
function createPrng(seed: number) {
  let s = seed % 2147483647;
  if (s <= 0) s += 2147483646;
  return () => {
    s = (s * 16807) % 2147483647;
    return (s - 1) / 2147483646;
  };
}

const METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE"] as const;

function generateAppSource(opts: GenOptions): string {
  const rand = createPrng(SEED);
  const lines: string[] = [
    "// GENERATED by scripts/generate-type-fixtures.ts (seed 424242) — do not edit by hand.",
    `// target=${opts.target} guardDensity=${opts.guardDensity} schemaDensity=${opts.schemaDensity}`,
    'import { z } from "zod";',
    'import { defineApp } from "../../../src/core/app";',
    'import { defineModule } from "../../../src/core/module";',
    'import { route } from "../../../src/core/route";',
    'import { guard } from "../../../src/core/guard";',
    'import { json, text, problem } from "../../../src/core/response";',
    "",
    "const authGuard = guard({",
    '  name: "authGuard",',
    "  handler: () => json(401, { error: 'unauthorized' }),",
    "});",
    "const adminGuard = guard({",
    '  name: "adminGuard",',
    "  handler: () => problem(403, { title: 'Forbidden' }),",
    "});",
    "",
    "// --- module routes (1/3 of total) ---",
  ];

  const moduleRoutes: string[] = [];
  const rootRoutes: string[] = [];
  let emitted = 0;
  let idx = 0;

  while (emitted < opts.target) {
    const method = METHODS[Math.floor(rand() * METHODS.length)]!;
    const withParams = rand() < 0.4;
    const withGuard = rand() < opts.guardDensity;
    const withSchema = rand() < opts.schemaDensity;
    const raw = rand() < 0.1;
    const inModule = idx % 3 === 0;
    const path = withParams ? `/res${idx}/:id${idx}` : `/res${idx}`;
    let block: string;

    if (raw) {
      // native raw response entry (direct Response value, no method map)
      block = `    ${JSON.stringify(path)}: new Response("raw ${idx}"),`;
    } else {
      const parts: string[] = [];
      if (withGuard) {
        const guardName = rand() < 0.5 ? "[authGuard]" : "[authGuard, adminGuard]";
        parts.push(`        before: ${guardName},`);
      }
      if (withParams) {
        parts.push(`        params: z.object({ id${idx}: z.coerce.number() }),`);
      }
      if (withSchema && method !== "GET") {
        parts.push(`        body: z.object({ name${idx}: z.string(), count: z.number() }),`);
      } else if (withSchema) {
        parts.push(`        query: z.object({ page${idx}: z.coerce.number(), tag: z.string().optional() }),`);
      }
      const status = method === "POST" ? 201 : 200;
      parts.push(`        handler: () => json(${status}, { ok: true, idx: ${idx} }),`);
      block =
        `    ${JSON.stringify(path)}: {\n      ${method}: route({\n` +
        parts.join("\n") +
        `\n      }),\n    },`;
    }

    if (inModule) moduleRoutes.push(block);
    else rootRoutes.push(block);
    emitted++;
    idx++;
  }

  lines.push("const featureModule = defineModule({");
  lines.push('  name: "featureModule",');
  lines.push("  routes: {");
  lines.push(...moduleRoutes);
  lines.push("  },");
  lines.push("});");
  lines.push("");
  lines.push("export const app = defineApp({");
  lines.push("  routes: {");
  lines.push(...rootRoutes);
  lines.push("  },");
  lines.push("  modules: [featureModule],");
  lines.push("});");
  lines.push("");
  lines.push("export default app;");
  return lines.join("\n");
}

const OUT_DIR = join(import.meta.dir, "..", "tests", "type-performance", "fixtures");
const SIZES = [25, 100, 500, 1000] as const;

mkdirSync(OUT_DIR, { recursive: true });
for (const size of SIZES) {
  const source = generateAppSource({
    target: size,
    guardDensity: 0.25,
    schemaDensity: 0.5,
  });
  const file = join(OUT_DIR, `app-${size}.ts`);
  writeFileSync(file, source);
  console.log(`wrote ${file} (${size} routes)`);
}
console.log("done (seed 424242)");
