/**
 * TypeScript performance bench (M3-017).
 *
 * Measures cold/warm `tsc --extendedDiagnostics` cost of the final
 * server/client contract over the committed M3-005 fixtures (25/100/500/1,000
 * routes), plus per-feature attribution variants (plain vs response-unions vs
 * guards vs schemas vs all) at a fixed 100-route size.
 *
 * Raw diagnostics are retained under benchmarks/typecheck/results/.
 *
 * Usage:
 *   bun run scripts/typebench.ts                 # full matrix
 *   bun run scripts/typebench.ts --scales 25,500 # subset
 *
 * This script is the canonical implementation behind the planned
 * `typebench:all` package script.
 */
import { execSync } from "node:child_process";
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dir, "..");
const OUT = join(ROOT, "benchmarks", "typecheck");
const ENTRIES = join(OUT, "entries");
const ATTR = join(OUT, "attribution");
const RESULTS = join(OUT, "results");
const TSC = join(ROOT, "node_modules", ".bin", "tsc");

const args = process.argv.slice(2);
const scalesFlagRaw = args.find((a) => a === "--scales" || a.startsWith("--scales="));
const scalesFlag = scalesFlagRaw === "--scales" ? "--scales=" : scalesFlagRaw;
const SCALES = (
  scalesFlag ? scalesFlag.split("=")[1]!.split(",").map(Number) : [25, 100, 500, 1000]
).sort((a, b) => a - b);

function sh(cmd: string, argsArray: string[]): { status: number; stdout: string } {
  const out = execSync([cmd, ...argsArray].join(" "), {
    cwd: ROOT,
    encoding: "utf8",
    maxBuffer: 256 * 1024 * 1024,
    stdio: ["ignore", "pipe", "pipe"],
  });
  return { status: 0, stdout: out };
}

function fixtureEntry(scale: number): string {
  return `// GENERATED by scripts/typebench.ts — do not edit by hand.
import app from "../../../tests/type-performance/fixtures/app-${scale}";
import { createClient } from "../../../src/client/create-client";
import type { AppContract } from "../../../src/core/contract";
import type { ClientCallResult, PathsForMethod } from "../../../src/client/types";

type API = AppContract<typeof app>;

// Force full per-path client-result instantiation for every method group.
export type GetResults = {
  [P in PathsForMethod<API, "GET"> as P & string]: ClientCallResult<API, P & string, "GET">;
};
export type PostResults = {
  [P in PathsForMethod<API, "POST"> as P & string]: ClientCallResult<API, P & string, "POST">;
};
declare const getResults: GetResults;
declare const postResults: PostResults;

export const client = createClient<API>({ baseUrl: "https://bench.test" });
void getResults;
void postResults;
`;
}

function tsconfigFor(entryRel: string, name: string): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "esnext",
        module: "esnext",
        moduleResolution: "bundler",
        lib: ["esnext"],
        types: ["@types/bun"],
        strict: true,
        noUncheckedIndexedAccess: true,
        exactOptionalPropertyTypes: true,
        verbatimModuleSyntax: true,
        isolatedModules: true,
        noEmit: true,
        skipLibCheck: true, // matches the developer-experience tsconfig; disclosed in report
        // Relative so generated configs stay identical across checkouts.
        tsBuildInfoFile: `results/${name}.tsbuildinfo`,
      },
      include: [entryRel],
    },
    null,
    2,
  );
}

type Metrics = {
  files?: number | undefined;
  types?: number | undefined;
  instantiations?: number | undefined;
  checkMs?: number | undefined;
  totalMs?: number | undefined;
  memoryMb?: number | undefined;
};

function parseDiagnostics(text: string): Metrics {
  const grab = (re: RegExp): number | undefined => {
    const m = text.match(re);
    if (!m) return undefined;
    const value = Number.parseFloat(m[1]!.replace(/s$/, ""));
    return Number.isNaN(value) ? undefined : value;
  };
  return {
    files: grab(/Files:\s+(\d+)/),
    types: grab(/Types:\s+(\d+)/),
    instantiations: grab(/Instantiations:\s+(\d+)/),
    checkMs: grab(/Check time:\s+([\d.]+)s/) !== undefined ? Math.round(grab(/Check time:\s+([\d.]+)s/)! * 1000) : undefined,
    totalMs: Math.round((grab(/Total time:\s+([\d.]+)s/) ?? 0) * 1000) || undefined,
    memoryMb: grab(/Memory used:\s+([\d.]+)K/) !== undefined ? Math.round(grab(/Memory used:\s+([\d.]+)K/)! / 1024) : undefined,
  };
}

type RunResult = { label: string; metrics: Metrics; rawFile: string };

function runOnce(name: string, cfgAbs: string, mode: "cold" | "warm"): RunResult {
  const extra = mode === "warm" ? ["--incremental"] : [];
  if (mode === "cold") {
    rmSync(join(RESULTS, `${name}.tsbuildinfo`), { force: true });
  }
  let stdout: string;
  try {
    ({ stdout } = sh(TSC, [
      "-p",
      cfgAbs,
      "--noEmit",
      "--pretty",
      "false",
      "--extendedDiagnostics",
      ...extra,
    ]));
  } catch (error) {
    const err = error as { stdout?: string };
    stdout = err.stdout ?? String(error);
  }
  if (/error TS\d+/.test(stdout)) {
    console.error(`TYPEBENCH-FAIL: TypeScript errors during ${name} (${mode}):`);
    console.error(stdout.split("\n").filter((l) => /error TS/.test(l)).slice(0, 10).join("\n"));
    process.exit(1);
  }
  const rawFile = join(RESULTS, `${name}.${mode}.txt`);
  writeFileSync(rawFile, stdout);
  return { label: name, metrics: parseDiagnostics(stdout), rawFile };
}

// ---------- attribution variant generation ----------

function variantSource(variant: string, routes = 100): string {
  const lines: string[] = [];
  lines.push(`// GENERATED by scripts/typebench.ts (${variant}, ${routes} routes) — do not edit by hand.`);
  lines.push(`import { z } from "zod";`);
  lines.push(`import { defineApp } from "../../../src/core/app";`);
  lines.push(`import { route } from "../../../src/core/route";`);
  if (variant === "guards" || variant === "all") {
    lines.push(`import { guard } from "../../../src/core/guard";`);
  }
  if (variant === "unions" || variant === "guards" || variant === "all") {
    lines.push(`import { json as json2, problem } from "../../../src/core/response";`);
  }
  lines.push(`import { json } from "../../../src/core/response";`);

  if (variant === "guards" || variant === "all") {
    lines.push(`const authGuard = guard({
      name: "authGuard",
      handler: () => json(401, { error: "unauthorized" }),
    });
    const adminGuard = guard({
      name: "adminGuard",
      handler: () => problem(403, { title: "Forbidden", code: "FORBIDDEN" }),
    });`);
  }

  const routesObj: string[] = [];
  for (let i = 0; i < routes; i++) {
    const body: string[] = [`"/r${i}": {`];
    const needsHandlerUnion = variant === "unions" || variant === "all";
    const guardRef =
      variant === "guards" || variant === "all"
        ? `\n        before: [authGuard, adminGuard],`
        : "";
    const schemaBits =
      variant === "schemas" || variant === "all"
        ? `
        params: z.object({ id${i}: z.coerce.number() }),
        query: z.object({ q${i}: z.string().optional(), page: z.coerce.number().optional() }),
        headers: z.object({ "x-seq": z.string().optional() }),
        body: z.object({ name: z.string(), count: z.number() }),`
        : "";
    if (needsHandlerUnion) {
      body.push(`GET: route({${guardRef}${schemaBits}
        handler: ({ params }: { params: Record<string, string> }) =>
          params.id${i} === undefined
            ? json(404, { missing: true })
            : ${i} % 3 === 0
            ? problem(410, { title: "Gone", code: "GONE" })
            : json(200, { ok: true, idx: ${i} }),
      }),`);
    } else if (variant === "guards") {
      body.push(`GET: route({${guardRef}
        handler: () => json(200, { ok: true, idx: ${i} }),
      }),`);
    } else if (variant === "schemas") {
      body.push(`PUT: route({${schemaBits}
        handler: () => json(200, { ok: true, idx: ${i} }),
      }),`);
    } else {
      body.push(`GET: route({
        handler: () => json(200, { ok: true, idx: ${i} }),
      }),`);
    }
    body.push(`},`);
    routesObj.push(body.join(""));
  }

  lines.push(`export default defineApp({ routes: { ${routesObj.join("\n")} } });`);
  return lines.join("\n");
}

// ---------- main ----------

mkdirSync(ENTRIES, { recursive: true });
mkdirSync(ATTR, { recursive: true });
mkdirSync(RESULTS, { recursive: true });

const environment = (() => {
  const bunVersion = Bun.version;
  const tscVersion = sh(TSC, ["--version"]).stdout.trim();
  let cpu = "unknown";
  let memGb = "unknown";
  try {
    const lscpu = execSync("lscpu | grep 'Model name' | head -1", { encoding: "utf8" });
    cpu = lscpu.split(":").pop()?.trim() ?? "unknown";
    const meminfo = readFileSync("/proc/meminfo", "utf8");
    memGb = `${Math.round(Number.parseInt(meminfo.match(/MemTotal:\s+(\d+)/)![1]!, 10) / 1024 / 1024)} GB`;
  } catch {
    /* environment details best-effort */
  }
  return { bunVersion, tscVersion, cpu, memGb };
})();

const summaryRows: string[] = [];
for (const scale of SCALES) {
  const entryRel = `entries/app-${scale}.entry.ts`;
  writeFileSync(join(ENTRIES, `app-${scale}.entry.ts`), fixtureEntry(scale));
  const cfgName = `app-${scale}`;
  const cfgAbs = join(OUT, `tsconfig.${cfgName}.json`);
  writeFileSync(cfgAbs, tsconfigFor(entryRel, cfgName));

  const cold = runOnce(cfgName, cfgAbs, "cold");
  runOnce(cfgName, cfgAbs, "warm"); // warms tsbuildinfo; second pass recorded
  const warm = runOnce(cfgName, cfgAbs, "warm");

  summaryRows.push(
    `| ${scale} | cold | ${cold.metrics.files ?? "-"} | ${cold.metrics.types ?? "-"} | ${cold.metrics.instantiations ?? "-"} | ${cold.metrics.checkMs ?? "-"} | ${cold.metrics.totalMs ?? "-"} | ${cold.metrics.memoryMb ?? "-"} |`,
  );
  summaryRows.push(
    `| ${scale} | warm(incremental) | ${warm.metrics.files ?? "-"} | ${warm.metrics.types ?? "-"} | ${warm.metrics.instantiations ?? "-"} | ${warm.metrics.checkMs ?? "-"} | ${warm.metrics.totalMs ?? "-"} | ${warm.metrics.memoryMb ?? "-"} |`,
  );
}

// Attribution at fixed 100 routes, cold runs only.
const variants = ["plain", "unions", "guards", "schemas", "all"] as const;
const attrRows: string[] = [];
let baselineCheckMs: number | undefined;
for (const variant of variants) {
  const fileRel = `attribution/${variant}-100.ts`;
  const fileAbs = join(ATTR, `${variant}-100.ts`);
  writeFileSync(fileAbs, variantSource(variant));
  const cfgName = `attr-${variant}`;
  const cfgAbs = join(OUT, `tsconfig.${cfgName}.json`);
  writeFileSync(cfgAbs, tsconfigFor(fileRel, cfgName));
  const run = runOnce(cfgName, cfgAbs, "cold");
  if (variant === "plain") baselineCheckMs = run.metrics.checkMs;
  const delta =
    baselineCheckMs !== undefined && run.metrics.checkMs !== undefined
      ? `+${run.metrics.checkMs - baselineCheckMs}`
      : "-";
  attrRows.push(
    `| ${variant} | ${run.metrics.checkMs ?? "-"} | ${delta} | ${run.metrics.instantiations ?? "-"} | ${run.metrics.memoryMb ?? "-"} |`,
  );
}

console.log("## Scale matrix (cold/warm)");
console.log("| routes | mode | files | types | instantiations | check ms | total ms | memory MB |");
console.log("|---|---|---|---|---|---|---|---|");
console.log(summaryRows.join("\n"));
console.log("");
console.log("## Feature attribution @100 routes (cold, delta vs plain)");
console.log("| variant | check ms | delta ms | instantiations | memory MB |");
console.log("|---|---|---|---|---|");
console.log(attrRows.join("\n"));
console.log("");
console.log(
  `## Environment\n- bun ${environment.bunVersion}; tsc ${environment.tscVersion}\n- cpu: ${environment.cpu}\n- memory: ${environment.memGb}`,
);

// Incremental-build artifacts are run-local state, not retained evidence.
for (const file of [join(RESULTS)]) {
  for (const f of readdirSync(file)) {
    if (f.endsWith(".tsbuildinfo")) {
      rmSync(join(file, f));
    }
  }
}
