/**
 * Production build for the starter: frontend (Vite), then the server pieces
 * that depend on the build output.
 *
 * 1. `vite build` emits dist/ with content-hashed assets and .vite/manifest.json.
 * 2. The asset manifest module is regenerated from that manifest: every
 *    emitted file becomes an explicit { path, cacheControl } mapping
 *    (ADR-0037) — exact mappings, no runtime scanning.
 * 3. The server entry is bundled with `bun build --target=bun` so
 *    `bun run start:built` runs a single built server file.
 */
import { readFileSync, writeFileSync, rmSync, readdirSync } from "node:fs";
import { join } from "node:path";

const STARTER = join(import.meta.dir, "..");

// 1. Frontend build.
const vite = Bun.spawnSync(["bunx", "vite", "build"], { cwd: STARTER, stdout: "pipe", stderr: "pipe" });
const viteOut = `${new TextDecoder().decode(vite.stdout)}${new TextDecoder().decode(vite.stderr)}`;
if (vite.exitCode !== 0) {
  console.error(viteOut);
  process.exit(1);
}

// 2. Regenerate the asset manifest from the Vite manifest.
type ViteManifest = Record<string, { file: string; isEntry?: boolean; css?: string[] }>;
const manifest = JSON.parse(readFileSync(join(STARTER, "dist", ".vite", "manifest.json"), "utf8")) as ViteManifest;
const lines: string[] = [];
for (const entry of Object.values(manifest)) {
  const file = entry.file;
  if (!file.startsWith("assets/")) continue;
  const url = `/${file}`;
  lines.push(`  [${JSON.stringify(url)}]: { path: resolve(process.cwd(), ${JSON.stringify(join("dist", file))}), cacheControl: "public, max-age=31536000, immutable" },`);
}
const generated = `/**
 * GENERATED by scripts/build.ts from the Vite build manifest — do not edit.
 *
 * ASSET_FILES: content-hashed build outputs mapped to explicit long-lived
 * caching (ADR-0037 object form). DIST: the built frontend root used as the
 * SPA shell source. Rebuild with \`bun run build\` after frontend changes.
 *
 * Paths resolve from the process working directory: the server is started
 * from the starter root via the package scripts (works identically for the
 * source entry and the bundled dist-server entry).
 */
import { resolve } from "node:path";

export const DIST = resolve(process.cwd(), "dist");

export const ASSET_FILES: Readonly<Record<string, { readonly path: string; readonly cacheControl: string }>> = {
${lines.join("\n")}
};
`;
writeFileSync(join(STARTER, "server", "asset-manifest.ts"), generated);

// 3. Server bundle (single built entry; Bun executes it directly).
const outDir = join(STARTER, "dist-server");
rmSync(outDir, { recursive: true, force: true });
const bundle = Bun.spawnSync(["bun", "build", "server/main.ts", "--target=bun", "--outdir", "dist-server"], {
  cwd: STARTER, stdout: "pipe", stderr: "pipe",
});
const bundleOut = `${new TextDecoder().decode(bundle.stdout)}${new TextDecoder().decode(bundle.stderr)}`;
if (bundle.exitCode !== 0) {
  console.error(bundleOut);
  process.exit(1);
}
const built = readdirSync(outDir).filter((f) => f.endsWith(".js"));
console.log(`build complete: dist/ (+${Object.keys(manifest).length} manifest entries), dist-server/${built.join(", ")}`);
